CREATE TABLE TEM.BIBIANA_TABLAGEN AS
select * from tablagen where table_code = 'BARRAZOLA' 'PERF_ECA'

INSERT INTO tablagen SELECT * FROM TEM.BIBIANA_TABLAGEN

SELECT * FROM TEM.BIBIANA_TABLAGEN
UPDATE TEM.BIBIANA_TABLAGEN SET TABLE_CODE = 'BARRAZOLA', LAST_UPDATE = NOW(), CREATION_DATE = NOW(), CREATION_USER = 'BTERRAZA', USER_UPDATE = ''

DELETE FROM TEM.BIBIANA_TABLAGEN WHERE TABLE_TYPE = 'PERF_ECA'