-- --CUANDO NO SE LE CARGAN INTERESES DE MORA
-- EJECUTAR ESTE QUERY Y REVISAR EN LA PARTE DE MSJ DE LA SALIDA ESTA LINEA _CONCEPTREC: (58,2,AVA,AVAL,"AVAL VENCIDO",1,4000,"")
-- Y TENER EN CUENTA EL PRIMER CAMPO, EN ESTE CASO 58, PARA LUEGO HACER EL UPDATE QUE ESTA AL FINAL DEL ARCHIVO, TAMBN TENER PRESENTE EL PERIODO Y LA UNIDAD DE NEGOCIO
SELECT 
                NEGOCIO
                ,CEDULA
                ,NOMBRE_CLIENTE
                ,CUOTA
                ,FECHA_VENCIMIENTO
                , NOW()::DATE - FECHA_VENCIMIENTO AS DIAS_VENCIDO_HOY
                ,VENCIMIENTO_MAYOR
                ,DIAS_VENCIDOS
                ,STATUS
                ,SUM(VALOR_ASIGNADO) AS VALOR_ASIGNADO
                ,SUM(DEBIDO_COBRAR) AS DEBIDO_COBRAR
                ,SUM(INTERES_MORA) AS INTERES_MORA
                ,SUM(GASTO_COBRANZA) AS GASTO_COBRANZA
            FROM SP_DETALLECARTERAXSANCION('201510','2','FA07141') AS COCO(NEGOCIO VARCHAR, CEDULA VARCHAR, NOMBRE_CLIENTE VARCHAR, CUOTA VARCHAR, DOCUMENTO VARCHAR, FECHA_VENCIMIENTO DATE, DIAS_VENCIDOS NUMERIC, VENCIMIENTO_MAYOR VARCHAR, STATUS VARCHAR, VALOR_ASIGNADO NUMERIC, DEBIDO_COBRAR NUMERIC, INTERES_MORA NUMERIC,GASTO_COBRANZA NUMERIC )  
                GROUP BY 
                NEGOCIO
                ,CEDULA
                ,NOMBRE_CLIENTE
                ,CUOTA
                ,FECHA_VENCIMIENTO
                ,VENCIMIENTO_MAYOR
                ,STATUS 
                ,DIAS_VENCIDOS           
                ORDER BY CUOTA::NUMERIC

/*
                SELECT * FROM SANCIONES_CONDONACIONES 
                --UPDATE SANCIONES_CONDONACIONES SET DIAS_RANGO_FIN = 2000
		WHERE PERIODO = 201510 AND ID_TIPO_ACTO = 1 AND ID_UNIDAD_NEGOCIO = 2
		AND ID_CONCEPTOS_RECAUDO IN (58,54,56) AND DESCRIPCION = 'INTERES X MORA';

*/
