-- SELECT * FROM ADMINISTRATIVO.PASIVO_VACACIONAL
-- SELECT * FROM ADMINISTRATIVO.NOVEDADES

SELECT 		N.NUMSOLICITUD,
                CASE WHEN (N.APROBADO)='S'THEN'APROBADO' ELSE CASE WHEN N.APROBADO = 'N' THEN 'RECHAZADO' ELSE CASE WHEN N.APROBADO = 'P' THEN 'PENDIENTE' END END END AS STATUS,
                CASE WHEN (N.REG_STATUS)=''THEN'ACTIVO' ELSE 'INACTIVO' END AS ESTADO,
                T.DESCRIPCION AS TIPO_NOVEDAD,
		CASE WHEN (T.DESCRIPCION) = 'INCAPACIDAD ' THEN ES.DESCRIPCION  ELSE '' END AS EPS,	
                --ES.DESCRIPCION AS EPS, 
                --T.ID AS ID_TIPO_NOVEDAD,
                FECHA_SOLICITUD::DATE, 
                CC_EMPLEADO AS IDENTIFICACION, 
                EM.NOMBRE_COMPLETO,
                FECHA_INI::DATE, 
                DURACION_DIAS, 
                FECHA_FIN::DATE, 
                --HORA_INI, 
                DURACION_HORAS, 
                --HORA_FIN, 
                R.DESCRIPCION AS RAZON, 
                --R.ID AS ID_RAZON,
                COD_ENFERMEDAD, 
                E.DESCRIPCION AS ENFERMEDAD, 
                N.DESCRIPCION, 
                --CASE WHEN APROBADO = 'S' THEN 'SI' ELSE 'NO' END AS APROBADO,
                APROBADO,
                --COMENTARIO, 
                FECHA_AUTORIZA::DATE,
                --REL.ID_USUARIO AS ID_JEFE_DIRECTO,
                --U.NOMBRE AS JEFE_DIRECTO, 
                N.USER_AUTORIZA AS ID_JEFE_DIRECTO,
                REMUNERADA, 
                FECHA_VISTO_BUENO::DATE, 
                USER_VISTO_BUENO, 
                N.OBSERVACIONES, 
                N.CREATION_DATE::date as fecha_creacion , 
                N.CREATION_USER as Usuario_creador, 
                --N.LAST_UPDATE, 
                --N.USER_UPDATE, 
                DIAS_COMPENSADOS,
                DIAS_A_PAGAR
                --RECOBRO,
                --ID_PROCESO,
                --P.DESCRIPCION AS PROCESO_ACTUAL,
                --N.ORIGEN,
                --CASE WHEN (N.REG_STATUS)='' THEN 'CHECKED' ELSE '' END AS CAMBIO
FROM 		ADMINISTRATIVO.NOVEDADES N
LEFT JOIN 	ADMINISTRATIVO.ENFERMEDADES E ON E.CODIGO = N.COD_ENFERMEDAD
INNER JOIN 	ADMINISTRATIVO.EMPLEADOS EM ON EM.IDENTIFICACION = N.CC_EMPLEADO
INNER JOIN	ADMINISTRATIVO.ENTIDADES_SALUD ES ON EM.ID_ENTIDAD_SALUD = ES.ID 
INNER JOIN 	ADMINISTRATIVO.TIPO_NOVEDAD T ON T.ID=N.ID_TIPO
LEFT JOIN 	ADMINISTRATIVO.RAZON_NOVEDAD R ON R.ID=N.RAZON
INNER JOIN 	USUARIOS U ON U.IDUSUARIO = N.USER_AUTORIZA
LEFT JOIN 	PROCESO_INTERNO P ON P.ID=N.ID_PROCESO
WHERE 		
		EM.REG_STATUS = ''
--AND 		FECHA_SOLICITUD::DATE BETWEEN '2018-01-01'::DATE AND '2018-06-27'::DATE 
ORDER BY 	N.FECHA_SOLICITUD DESC;

-- select * from administrativo.EMPLEADOS  limit 100
-- select * from administrativo.entidades_salud LIMIT 100

