update opav.sl_ocs_detalle set costo_unitario_compra = '565476.66',  costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '1180500' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '29620.21',  costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '8800430' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '29620.21',  costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '8800490' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '508928.99', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '5050065' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '49815.80',  costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9342220' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '107709.84', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9342250' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '184453.10', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9671688' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '53854.92',  costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9660970' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '1117489.5', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9670808' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '297548.43', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9672180' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '134637.30', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9672183' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '148101.03', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9672184' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '184453.10', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9672186' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '125212.69', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9672318' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '241000.77', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9672348' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '137330.05', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9673008' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '367559.83', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9674184' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '282738.33', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9660205' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '105017.09', costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '3052000' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');  
update opav.sl_ocs_detalle set costo_unitario_compra = '83475.1',   costo_total_compra = cantidad_solicitada * costo_unitario_compra where referencia_externa = '9340000' and id_ocs in (select id from opav.sl_orden_compra_servicio where cod_ocs = 'OC02736-1');


