SELECT * FROM opciones_menu_modulos WHERE id = 10;

MCASTILLO,HCUELLO,EDGARGM87,MMEDINA,PPLATA,WSUAREZ,OESCOBAR,TLUCHETTA,DRBLANCO,MCAMARGO,DVALENCIA,KRINCON,CFONTALVO,AYUNEZ,GBARRIOS,UCHARRIS,JMORA,AVENDRIES,GESPRIELLA,ABOLIVAR,ECASTRO,LGARCIAM,EROSALES,ECRESPO,POSPINOB ,JDBERMUDEZ,YSUAREZC,GGALEANO,BMENDOZA, BTERRAZA, DLARA