-- FUNCTION: NEGOCIO_INDEMNIZADO(CHARACTER VARYING)

-- DROP FUNCTION NEGOCIO_INDEMNIZADO(CHARACTER VARYING);

CREATE OR REPLACE FUNCTION NEGOCIO_INDEMNIZADO(_NEGOCIO CHARACTER VARYING, _DOCUMENTO CHARACTER VARYING)
  RETURNS TEXT AS
$BODY$

DECLARE

 RETORNO VARCHAR:='';
  
BEGIN
	

	
	      IF ((SUBSTRING(_NEGOCIO,1,2) = 'MC') OR (SUBSTRING(_NEGOCIO,1,2) = 'FE'))  THEN
			            IF (SELECT NEGOCIO FROM ADMINISTRATIVO.CONTROL_INDEMNIZACION_FIANZA WHERE NEGOCIO = _NEGOCIO AND DOCUMENTO = _DOCUMENTO) IS NOT NULL THEN
			            			RETORNO:='S';
			            	 ELSE 
			            	 		RETORNO:='N';
			            END IF;
	      ELSE
	        	  		IF (SELECT NEGOCIO FROM ADMINISTRATIVO.CONTROL_INDEMNIZACION_FENALCO WHERE NEGOCIO = _NEGOCIO AND DOCUMENTO = _DOCUMENTO) IS NOT NULL THEN
			            			RETORNO:='S';
			            	ELSE 
			            	 		RETORNO:='N';
			                END IF;
              END IF;  



	

	RETURN RETORNO;

END;
$BODY$
  LANGUAGE PLPGSQL VOLATILE;
ALTER FUNCTION NEGOCIO_INDEMNIZADO(CHARACTER VARYING, CHARACTER VARYING)
  OWNER TO POSTGRES;
