SELECT ESTADO_NEG, ACTIVIDAD FROM NEGOCIOS WHERE COD_NEG = 'MC14580' -- DES , T
-- UPDATE NEGOCIOS SET ESTADO_NEG = 'T', ACTIVIDAD = 'DES' WHERE COD_NEG = 'MC14580' -- DES , T
SELECT ESTADO_SOL FROM SOLICITUD_AVAL WHERE COD_NEG = 'MC14580' -- DES , T
-- UPDATE SOLICITUD_AVAL SET ESTADO_SOL = 'T' WHERE COD_NEG = 'MC14580' -- DES , T

-----------------------------------------------------------------------------------------------------------

SELECT ESTADO_NEG, ACTIVIDAD FROM NEGOCIOS WHERE COD_NEG = 'MC15617' -- ANA , R
-- UPDATE NEGOCIOS SET ESTADO_NEG = 'R', ACTIVIDAD = 'ANA' WHERE COD_NEG = 'MC15617' -- ANA , R
SELECT ESTADO_SOL FROM SOLICITUD_AVAL WHERE COD_NEG = 'MC15617' -- ANA , R
-- UPDATE SOLICITUD_AVAL SET ESTADO_SOL = 'R' WHERE COD_NEG = 'MC15617' -- ANA , R
