update apicredit.usuarios_portal set reg_status = 'A', claveencr = 'xxxxxxx'where idusuario in ('AAMARIS','AAPARICIO',
'AARRIETA',
'AGUTIERREZ',
'APORTILLA',
'CAMILORODR', 
'CBOLIVAR', 
'CGUZMAN', 
'DBABILONIA', 
'DFONTALVOS', 
'KPEREZE', 
'LBUELVAS', 
'LOVALLE', 
'LTESILLOM', 
'POSPINO', 
'SANILLO', 
'YBRAVO', 
'YVEGA')