

select 
    MC_____NUMERO____PERIOD_B,
    COUNT(*) 
from 
    APOTEOSYS.mc____ 
where 
    MC_____CODIGO____CONTAB_B = 'FINT'
	AND MC_____CODIGO____TD_____B = 'CXCN'
	AND MC_____CODIGO____CD_____B = 'PMFN'
	AND MC_____CODIGO____PF_____B = 2017
--AND MC_____NUMERO____PERIOD_B = 1
GROUP BY MC_____NUMERO____PERIOD_B
ORDER BY MC_____NUMERO____PERIOD_B
;
  
  
  SELECT *
FROM APOTEOSYS.MENSAJ
WHERE MENSAJ_NUMEMENS__B IN (2111);

SELECT mcte.MCTEMP_CADERRVAL_B, 
  mcte.*
FROM APOTEOSYS.MCTEMP mcte
WHERE mcte.MCTEMP_SECUINTE__CEP____B = '9942'; AND MCTEMP_CADERRVAL_B IS NOT NULL; --AND mcte.MC_____NUMERO____B=57552
ORDER BY mcte.MC_____SECUINTE__DCD____B;

SELECT * FROM APOTEOSYS.CPC___  WHERE CPC____CODIGO____B =  28151004;

SELECT * FROM APOTEOSYS.SCD___ WHERE SCD____NUMDOCSOP_B = '057';


SELECT * FROM APOTEOSYS.SCD___ WHERE SCD____CODIGO____CPC____B=23200101;

SELECT * FROM APOTEOSYS.MC____ WHERE MC_____CODIGO____CD_____B='CCSL';

SELECT * FROM APOTEOSYS.MC____ WHERE MC_____CODIGO____CD_____B='NCSL' AND MC_____NUMERO____B=57194;

SELECT * FROM APOTEOSYS.SCD___ WHERE SCD____NUMDOCSOP_B='016';

--verificar 
select * from APOTEOSYS.CD____ where CD_____CODIGO____B='NCCF';
select 257334309 -	10252800 from dual;