SELECT * FROM APOTEOSYS.DV____;


SELECT 
     MC.MC_____CODIGO____CONTAB_B AS EMPRESA
    ,MC.MC_____IDENTIFIC_TERCER_B AS TERCERO
    ,P.TERCER_NOMBEXTE__B AS NOMBRE_TERCERO
    ,MC.MC_____CODIGO____TD_____B AS TIPODOC
    ,TD.TD_____NOMBRE____B AS NOM_TIPODOC
    ,MC.MC_____NUMERO____B AS DOCUMENTO
    ,MC.MC_____CODIGO____CD_____B AS CONCEPTO
    ,CD.CD_____NOMBRE____B AS NOMBRE_CONCEPTO
    ,MC.MC_____CODIGO____PF_____B  AS ANIO
    ,MC.MC_____NUMERO____PERIOD_B AS MES
    ,CONCAT(MC.MC_____CODIGO____PF_____B , LPAD(MC.MC_____NUMERO____PERIOD_B,2,'0')) AS PERIODO
    ,MC.MC_____CODIGO____PC_____B AS CODIGO_PUC
    ,PC.PC_____NOMBRE____B AS NOMBRE_PUC
    ,CASE WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='1' THEN 'Activo'
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='2' THEN 'Pasivo'
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='3' THEN 'Patrimonio'
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='4' THEN 'Ingresos'
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='5' THEN 'Gastos'
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='6' THEN 'Costos Ventas'
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='7' THEN 'Costos Produccion o de Operacion'
     END AS CLASE
    ,MC.MC_____CODIGO____CPC____B AS CUENTA
    ,CPC.CPC____NOMBRE____B AS NOMBRE_CUENTA
    ,MC.MC_____NUMDOCSOP_B AS NUMERO_DOCUMENTO
    ,MC.MC_____OBSERVACI_B AS OBSERVACION
    ,MC.MC_____FECHORCRE_B AS FECHA_CREACION
    ,MC.MC_____FECHVENC__B AS FECHA_VENCIMIENTO
    ,MC.MC_____AUTOCREA__B AS USUARIO_CREACION
    ,MC.MC_____AUTULTMOD_B AS USUARIO_AUTUALIZACION
    ,MC.MC_____FEHOULMO__B AS FECHA_ULTIMA_ACTULIZACION
    ,NVL(MC.MC_____CODIGO____CU_____B,'SIN CENTRO DE COSTO') AS CENTRO_COSTO
    ,NVL(CU.CU_____NOMBRE____B,'SIN CENTRO DE COSTO') AS NOMBRE_CENTRO_COSTO
    ,MC.MC_____DEBMONLOC_B AS VLR_DEBITO
    ,MC.MC_____CREMONLOC_B AS VLR_CREDITO
    ,CASE WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='1' THEN (MC.MC_____DEBMONLOC_B-MC.MC_____CREMONLOC_B)
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='2' THEN (MC.MC_____CREMONLOC_B-MC.MC_____DEBMONLOC_B)
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='3' THEN (MC.MC_____CREMONLOC_B-MC.MC_____DEBMONLOC_B)
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='4' THEN (MC.MC_____CREMONLOC_B-MC.MC_____DEBMONLOC_B)
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='5' THEN (MC.MC_____DEBMONLOC_B-MC.MC_____CREMONLOC_B)
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='6' THEN (MC.MC_____DEBMONLOC_B-MC.MC_____CREMONLOC_B)
          WHEN SUBSTR(CAST(MC.MC_____CODIGO____CPC____B  AS VARCHAR2(100)),1,1)='7' THEN (MC.MC_____DEBMONLOC_B-MC.MC_____CREMONLOC_B)
     END AS SALDO
 ,MC.MC_____REFERENCI_B AS REFERENCIA
 ,Ciu.Ciudad_Nombre____B CIUDAD
 ,Dep.Depart_Nombre____B DEPARTAMENTO
 ,TERDV.TERCER_NOMBCOMP__B AS ASESOR
FROM APOTEOSYS.MC____ MC
INNER JOIN APOTEOSYS.TD____  TD ON (TD.TD_____CODIGO____B=MC.MC_____CODIGO____TD_____B)
INNER JOIN APOTEOSYS.CD____ CD ON (CD.CD_____CODIGO____B=MC.MC_____CODIGO____CD_____B  AND CD.CD_____CODIGO____TD_____B =TD.TD_____CODIGO____B)
INNER JOIN APOTEOSYS.PC____ PC ON (PC.PC_____CODIGO____B=MC.MC_____CODIGO____PC_____B)
INNER JOIN APOTEOSYS.CPC___ CPC ON (PC.PC_____CODIGO____B=CPC.CPC____CODIGO____PC_____B  AND CPC.CPC____CODIGO____B=MC.MC_____CODIGO____CPC____B  )
INNER JOIN APOTEOSYS.TERCER P ON (P.TERCER_IDENTIFIC_B=MC.MC_____IDENTIFIC_TERCER_B)
LEFT JOIN APOTEOSYS.CU____ CU ON (CU.CU_____CODIGO____B=MC.MC_____CODIGO____CU_____B )
INNER JOIN APOTEOSYS.CIUDAD ciu on P.Tercer_Codigo____Ciudad_B = Ciu.Ciudad_Codigo____B
inner join Depart dep on Ciu.Ciudad_Codigo____Depart_B = Dep.Depart_Codigo____B
LEFT JOIN APOTEOSYS.DV____ FACT ON (MC.MC_____CODIGO____CONTAB_B = FACT.DV_____CODIGO____CONTAB_B 
                                    AND 'FACL' = FACT.DV_____CODIGO____DS_____B 
                                    AND FACT.DV_____FECHA_____B = MC.MC_____FECHA_____B 
                                    AND FACT.DV_____NUMERO____B = MC.MC_____NUMERO____B)
LEFT JOIN APOTEOSYS.TERCER TERDV ON (TERDV.TERCER_IDENTIFIC_B = FACT.DV_____IDENTIFIC_VENDED_B)
WHERE CONCAT(MC.MC_____CODIGO____PF_____B , LPAD(MC.MC_____NUMERO____PERIOD_B,2,'0'))  BETWEEN '201701' AND REPLACE(SUBSTR(TO_CHAR(SYSDATE, 'YYYY-MM-DD'),1,7),'-','')
AND MC.MC_____CODIGO____CONTAB_B='GEOT' AND MC.MC_____CODIGO____TD_____B IN ('FACN','CXCN','IMPU','ANUL')
AND MC.MC_____CODIGO____CPC____B LIKE '41%';



SELECT * FROM APOTEOSYS.DV____ WHERE  DV_____NUMERO____B ='105761';
select * from APOTEOSYS.TERCER where TERCER_IDENTIFIC_B ='22739645'; 

